name: SCDF Tanzu Observability Sink CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: |
          mvn -B package
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v1
        with:
          name: scdf-tanzu-observability-sink-0.0.1-SNAPSHOT.jar
          path: ${{ github.workspace }}/target/scdf-tanzu-observability-sink-0.0.1-SNAPSHOT.jar
  commit-to-releases-branch:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v1
        with:
          name: scdf-tanzu-observability-sink-0.0.1-SNAPSHOT.jar
          path: ${{ github.workspace }}/
      - name: Commit JAR to releases branch
        run: |
          mkdir ${{ github.workspace }}/repo
          cd ${{ github.workspace }}/repo
          git clone -b releases https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          cd scdf-tanzu-observability-sink
          cp ${{ github.workspace }}/scdf-tanzu-observability-sink-0.0.1-SNAPSHOT.jar ${{ github.workspace }}/repo/scdf-tanzu-observability-sink/
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add current scdf-tanzu-observability-sink release archive"
          git push
